version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: members
      POSTGRES_USER: team5
      POSTGRES_PASSWORD: team5
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
